name: Monorepo Deploy
on:
  push:
    branches:
      - master

env:
  HOST: 47.103.10.185
  USERNAME: ${{ secrets.SSH_USERNAME }}
  PASSWORD: ${{ secrets.SSH_PASSWORD }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Build Backend
        run: |
          pnpm install
          pnpm --workspace-root run build:server || (echo "Build failed, see logs below:" && cat ./packages/server/dist/build.log)
      - name: Package backend build folder
        run: |
          tar -czf server.tar.gz packages/server/dist
      - name: Upload to Deploy Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
          source: 'server.tar.gz'
          target: /path/to/deploy/backends
      - name: Deploy Backend to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.HOST }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
          script: |
            cd /path/to/deploy/backends
            rm -rf old-backend && mv current-backend old-backend || true
            tar -xzvf server.tar.gz -C /path/to/deploy/backends/current-backend
            node current-backend/main.js
